version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Running Prisma migrations..."
      - npx prisma migrate deploy
      - echo "Building Next.js app..."
      - npm run build

artifacts:
  baseDirectory: .next
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*
