version: 0.2

backend:
  phases:
    install:
      commands:
        - npm ci
    build:
      commands:
        - npx prisma migrate deploy

frontend:
  phases:
    install:
      commands:
        - npm ci
    build:
      commands:
        - npm run build

artifacts:
  baseDirectory: .next
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*
